version: 2.1
jobs:
  lint-scripts:
    docker:
      - image: koalaman/shellcheck-alpine
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ca:a9:91:05:b7:e2:0b:bc:ec:fb:6f:96:31:f4:d2:dd"
      - checkout
      - run:
          name: lint
          command: shellcheck -x .circleci/*.sh
  release-charts:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ca:a9:91:05:b7:e2:0b:bc:ec:fb:6f:96:31:f4:d2:dd"
      - checkout
      - run:
          command: |
            echo "export GIT_REPOSITORY_URL=https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME" >> $BASH_ENV
            echo "export GIT_USERNAME=$CIRCLE_PROJECT_USERNAME" >> $BASH_ENV
            echo "export GIT_REPOSITORY_NAME=$CIRCLE_PROJECT_REPONAME" >> $BASH_ENV
            .circleci/install_tools.sh
            .circleci/release.sh

workflows:
  version: 2.1
  release:
    jobs:
      - lint-scripts
      - release-charts:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: main
