apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appname }}-webhook-configmap
  namespace: {{ .Release.Namespace }}
data:
  sidecarconfig.yaml: {{ toYaml .Values.config.sidecar | indent 2 }}
  mutationconfig.yaml: {{ toYaml .Values.config.mutation | indent 2 }}
