---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.appname }}-webhook-cfg
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Values.appname }}-certificate
webhooks:
  - clientConfig:
      service:
        name: {{ .Values.appname }}
        namespace: {{ .Release.Namespace }}
        path: /mutate
    failurePolicy: Fail
    name: {{ .Values.appname }}.sfdc.internal
    admissionReviewVersions:
      - 'v1'
    sideEffects: None
    namespaceSelector:
      matchExpressions:
        - key: sidecar-injection
          operator: NotIn
          values: ["disabled"]
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
