apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "telegraf-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ template "telegraf-operator.fullname" . }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ template "telegraf-operator.fullname" . }}"
  template:
    metadata:
      labels:
        app: "{{ template "telegraf-operator.fullname" . }}"
{{- if eq .Values.certManager.enable false }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/tls.yaml") . | sha256sum }}
{{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            {{ toYaml .Values.livenessProbe | nindent 12 }}
          args:
            - "--telegraf-default-class={{ .Values.classes.default }}"
            - --telegraf-classes-directory=/etc/telegraf-operator
            - --enable-default-internal-plugin
            - "--telegraf-image={{ .Values.image.sidecarImage }}"
            {{- if eq .Values.requireAnnotationsForSecret true }}
            - "--require-annotations-for-secret"
            {{- end }}
            {{- if eq .Values.hotReload true }}
            - "--telegraf-watch-config=inotify"
            {{- end }}
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          ports:
            - name: https
              containerPort: 9443
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/certs
              name: certs
              readOnly: true
            - mountPath: /etc/telegraf-operator
              name: classes
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "telegraf-operator.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: certs
        secret:
          secretName: telegraf-operator-tls
      - name: classes
        secret:
          secretName: {{ .Values.classes.secretName }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
