{{- if .Values.classes.data }}
{{- $fullName := include "telegraf-operator.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.classes.secretName }}
  labels:
    app: {{ $fullName | quote }}
stringData: {{ .Values.classes.data | toYaml | nindent 2 }}
type: Opaque
{{- end }}
