apiVersion: v1
kind: Service
metadata:
  name: "{{ template "telegraf-operator.fullname" . }}"
  labels:
    app: "{{ template "telegraf-operator.fullname" . }}"
  annotations:
    {{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
{{ toYaml .Values.service.ports | indent 4 }}
  selector:
    app: "{{ template "telegraf-operator.fullname" . }}"
