replicaCount: 3

image:
  repository: quay.io/influxdb/telegraf-operator
  pullPolicy: IfNotPresent
  sidecarImage: "docker.io/library/telegraf:1.19"

apiVersionOverrides:
  # -- String to override apiVersion of certmanager resources rendered by this helm chart
  certmanager: "" # cert-manager.io/v1

certificate:
  auto_generate: false
  # -- Certificate manager domain
  domain: telegraf-operator.example.com
  issuer:
    # -- Certificate manager issuer
    kind: # ClusterIssuer
    # -- Certificate manager name
    name: # letsencrypt
  # -- Certificate manager additional hosts
  additionalHosts: []
  # -- Certificate manager secret name
  secretName: telegraf-operator-tls

classes:
  secretName: "telegraf-operator-classes"
  default: "base"
  data:
    base: |
      [[outputs.prometheus_client]]
        listen = ":9273"
        metric_version = 2
        path = "/metrics"
        collectors_exclude = ["gocollector", "process"]
      [global_tags]
        env = "ci"
        hostname = "$HOSTNAME"
        nodename = "$NODENAME"
        type = "base"

certManager:
  enable: false

imagePullSecrets: []

nameOverride: ""

fullnameOverride: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  # readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

requireAnnotationsForSecret: false
# allow hot reload ; disabled by default to support versions of telegraf
# that do not support hot-reload and --watch-config flag
hotReload: false

service:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 9443

rbac:
  # -- Rbac settings
  create: true
  serviceAccountAnnotations: {}
  serviceAccountName: ""
  annotations:
    {}
    # annotation1: "value1"
    # annotation2: "value2"
    # annotation3: "value3"

# -- Pod annotations
podAnnotations: {}

# -- Additionals labels
labels: {}

revisionHistoryLimit: 0
